# Generated by Django 5.2.6 on 2025-11-08 13:06

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Kode mata kuliah (misal: CS101)', max_length=20, unique=True)),
                ('name', models.CharField(help_text='Nama mata kuliah', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Deskripsi mata kuliah', null=True)),
                ('credits', models.IntegerField(help_text='Jumlah SKS', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)])),
                ('semester', models.CharField(choices=[('1', 'Semester 1'), ('2', 'Semester 2'), ('3', 'Semester 3'), ('4', 'Semester 4'), ('5', 'Semester 5'), ('6', 'Semester 6'), ('7', 'Semester 7'), ('8', 'Semester 8')], help_text='Semester', max_length=1)),
                ('major', models.CharField(choices=[('artificial_intelligence_and_robotics', 'AIR'), ('business_mathematics', 'BM'), ('digital_business_technology', 'DBT'), ('product_design_engineering', 'PDE'), ('food_business_technology', 'FBT')], help_text='Program studi untuk mata kuliah ini', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instructor', models.ForeignKey(blank=True, help_text='Dosen pengampu', limit_choices_to={'role': 'instructor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses_taught', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ['semester', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('dropped', 'Dropped')], default='active', help_text='Status pendaftaran', max_length=20)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('assignment_score', models.DecimalField(blank=True, decimal_places=2, help_text='Nilai tugas (0-100)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('midterm_score', models.DecimalField(blank=True, decimal_places=2, help_text='Nilai UTS (0-100)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('final_score', models.DecimalField(blank=True, decimal_places=2, help_text='Nilai UAS (0-100)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('final_grade', models.DecimalField(blank=True, decimal_places=2, help_text='Nilai akhir (0-100)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('letter_grade', models.CharField(blank=True, choices=[('A', 'A (4.0)'), ('A-', 'A- (3.7)'), ('B+', 'B+ (3.3)'), ('B', 'B (3.0)'), ('B-', 'B- (2.7)'), ('C+', 'C+ (2.3)'), ('C', 'C (2.0)'), ('D', 'D (1.0)'), ('E', 'E (0.0)')], help_text='Nilai huruf', max_length=2, null=True)),
                ('remarks', models.TextField(blank=True, help_text='Catatan dari dosen', null=True)),
                ('graded_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='users.course')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='grades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Grade',
                'verbose_name_plural': 'Grades',
                'ordering': ['-enrolled_at'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(limit_choices_to={'role': 'student'}, related_name='enrolled_courses', through='users.Grade', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='grade',
            index=models.Index(fields=['student', 'status'], name='users_grade_student_90999a_idx'),
        ),
        migrations.AddIndex(
            model_name='grade',
            index=models.Index(fields=['course', 'status'], name='users_grade_course__3c9198_idx'),
        ),
        migrations.AddIndex(
            model_name='grade',
            index=models.Index(fields=['letter_grade'], name='users_grade_letter__ebd696_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together={('student', 'course')},
        ),
    ]
