# Generated by Django 5.2.6 on 2025-11-08 13:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_course_grade_course_students_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grade',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='grade',
            name='users_grade_student_90999a_idx',
        ),
        migrations.RemoveIndex(
            model_name='grade',
            name='users_grade_course__3c9198_idx',
        ),
        migrations.RemoveIndex(
            model_name='grade',
            name='users_grade_letter__ebd696_idx',
        ),
        migrations.RenameField(
            model_name='grade',
            old_name='enrolled_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='graded_at',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='status',
        ),
        migrations.AddField(
            model_name='grade',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='credits',
            field=models.IntegerField(choices=[(2, '2 SKS'), (3, '3 SKS'), (4, '4 SKS'), (6, '6 SKS')], help_text='Jumlah SKS'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='assignment_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='grade',
            name='final_grade',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='final_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='grade',
            name='letter_grade',
            field=models.CharField(blank=True, choices=[('A', 'A (4.0)'), ('A-', 'A- (3.7)'), ('B+', 'B+ (3.3)'), ('B', 'B (3.0)'), ('B-', 'B- (2.7)'), ('C+', 'C+ (2.3)'), ('C', 'C (2.0)'), ('D', 'D (1.0)'), ('E', 'E (0.0)')], editable=False, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='midterm_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
