# Generated by Django 5.2.6 on 2025-11-08 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_grade_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='is_active',
        ),
    ]
